[[redirects]]
  from = "/api/standings"
  to = "/.netlify/functions/nhl?type=standings"
  status = 200
  force = true

[[redirects]]
  from = "/api/scores"
  to = "/.netlify/functions/nhl?type=scores"
  status = 200
  force = true

[[redirects]]
  from = "/api/insights"
  to = "/.netlify/functions/nhl?type=insights"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[functions."generate-insights"]
  schedule = "0 * * * *"

[build]
  publish = "."
