[[redirects]]
  from = "/api/standings"
  to = "/.netlify/functions/nhl/standings"
  status = 200

[[redirects]]
  from = "/api/scores"
  to = "/.netlify/functions/nhl/scores"
  status = 200

[[redirects]]
  from = "/api/insights"
  to = "/.netlify/functions/nhl/insights"
  status = 200

[build]
  publish = "."
